# Generated by Django 3.0.3 on 2020-02-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
