# Generated by Django 3.0.3 on 2020-02-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_trash_paper', models.FloatField()),
                ('collected_trash_food', models.FloatField()),
                ('collected_trash_plastic', models.FloatField()),
                ('user', models.IntegerField()),
            ],
        ),
    ]
