# Generated by Django 3.0.3 on 2020-02-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tukang_sampah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='collected_trash_food',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='collected_trash_paper',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='collected_trash_plastic',
            field=models.FloatField(default=0),
        ),
    ]
